# Global root definitions
# History of changes:
#
# 27 Mar 2019              creation

# Get root path
GLOBALROOTDIR              := $(shell dirname\
                                 $(realpath $(lastword $(MAKEFILE_LIST)))\
                              )/


#
# Build configurations
#

RASPDEBUG                  := dbg
RASPREL                    := rel


#
# All projects
#

# Top level folders - type of files inside folder
TOPLIB                     := lib
TOPBIN                     := bin
TOPOBJ                     := obj
TOPSRC                     := src
TOPINC                     := inc

# Top level categories
# Top Level Folder followed by name of project category
LIBCAT_DATASTRUCT          := datastruct
LIBCAT_ENCODE              := encode
LIBCAT_NET                 := net
BINCAT_NET                 := net
BINCAT_AI                  := ai

# All projects (first six chars are top level folders/categories)
LIBDAT_CYCBUF              := cycbuf
LIBDAT_OCTREE              := octree
LIBENC_BECODE              := becode
LIBENC_ELGAMAL             := elgamal
LIBNET_TCPLIB              := tcplib
BINNET_ETHFRAME            := ethframe
BINAI_BEHAVE               := behave

#
# Additional paths
#

# Full paths at top level
TOPLIBDIR                  := $(GLOBALROOTDIR)$(TOPLIB)/
TOPBINDIR                  := $(GLOBALROOTDIR)$(TOPBIN)/
TOPOBJDIR                  := $(GLOBALROOTDIR)$(TOPOBJ)/
TOPSRCDIR                  := $(GLOBALROOTDIR)$(TOPSRC)/
TOPINCDIR                  := $(GLOBALROOTDIR)$(TOPINC)/
